# Generated by Django 4.2.1 on 2024-09-22 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='dog_size',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='is_available',
        ),
    ]
