# Generated by Django 4.2.15 on 2024-09-12 07:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('photo1', models.ImageField(upload_to='carousel/')),
                ('textbox1', models.CharField(blank=True, max_length=200, null=True)),
                ('photo2', models.ImageField(upload_to='carousel/')),
                ('textbox2', models.CharField(blank=True, max_length=200, null=True)),
                ('photo3', models.ImageField(upload_to='carousel/')),
                ('textbox3', models.CharField(blank=True, max_length=200, null=True)),
                ('photo4', models.ImageField(upload_to='carousel/')),
                ('textbox4', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
