# Generated by Django 4.2.15 on 2024-09-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
