# Generated by Django 5.1.1 on 2024-09-12 17:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_carousel_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('intro_text', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('client_name1', models.CharField(max_length=100)),
                ('client_image1', models.ImageField(upload_to='clients/')),
                ('client_intro1', models.CharField(max_length=200)),
                ('client_name2', models.CharField(max_length=100)),
                ('client_image2', models.ImageField(upload_to='clients/')),
                ('client_intro2', models.CharField(max_length=200)),
                ('client_name3', models.CharField(max_length=100)),
                ('client_image3', models.ImageField(upload_to='clients/')),
                ('client_intro3', models.CharField(max_length=200)),
                ('client_name4', models.CharField(max_length=100)),
                ('client_image4', models.ImageField(upload_to='clients/')),
                ('client_intro4', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='carousel',
            name='textbox1',
            field=models.CharField(default='Su meilė ir kruopštumu', max_length=200),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='textbox2',
            field=models.CharField(default='Mūsų mylimiausi klientai', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='textbox3',
            field=models.CharField(default='Kiekvieną dieną kaip šventė', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='textbox4',
            field=models.CharField(default='Visi laukiami', max_length=200, null=True),
        ),
    ]
