# Generated by Django 4.2.15 on 2024-09-16 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
