# Generated by Django 5.1.1 on 2024-09-12 18:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_us',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Price_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('combing1', models.IntegerField(blank=True, max_length=10)),
                ('combing2', models.IntegerField(blank=True, max_length=10)),
                ('showering1', models.IntegerField(blank=True, max_length=10)),
                ('showering2', models.IntegerField(blank=True, max_length=10)),
                ('drying1', models.IntegerField(blank=True, max_length=10)),
                ('drying2', models.IntegerField(blank=True, max_length=10)),
                ('consult1', models.IntegerField(blank=True, max_length=10)),
            ],
        ),
    ]
