# Generated by Django 5.1.1 on 2024-09-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price_table',
            name='consult2',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='price_table',
            name='combing1',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='price_table',
            name='combing2',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='price_table',
            name='consult1',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='price_table',
            name='drying1',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='price_table',
            name='drying2',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='price_table',
            name='showering1',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='price_table',
            name='showering2',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
