# Generated by Django 5.1.1 on 2024-09-12 18:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_price_table_consult2_alter_price_table_combing1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='price_table',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='price_table',
            name='combing1',
            field=models.IntegerField(default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='price_table',
            name='combing2',
            field=models.IntegerField(default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='price_table',
            name='consult1',
            field=models.IntegerField(default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='price_table',
            name='consult2',
            field=models.IntegerField(default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='price_table',
            name='drying1',
            field=models.IntegerField(default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='price_table',
            name='drying2',
            field=models.IntegerField(default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='price_table',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='price_table',
            name='showering1',
            field=models.IntegerField(default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='price_table',
            name='showering2',
            field=models.IntegerField(default=0, max_length=10, null=True),
        ),
    ]
