# Generated by Django 4.2.15 on 2024-09-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_price_table_is_active_alter_price_table_combing1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_table',
            name='combing1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='price_table',
            name='combing2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='price_table',
            name='consult1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='price_table',
            name='consult2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='price_table',
            name='drying1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='price_table',
            name='drying2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='price_table',
            name='showering1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='price_table',
            name='showering2',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
